name: Deploy to Github Pages
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # - run: npm run build --if-present
      - run: npm test
    # gh-pages-deploy:
    #   name: Deploying to Github Pages
    #   runs-on: ubuntu-latest
    #   steps:
    #       - uses: actions/checkout@v2
    #       - uses: actions/setup-node@v2
    #         with:
    #           node-version: '12'
    #       - name: Install packages
    #         run: npm i
    #       - name: Set Creds
    #         run: git config user.name "<username>" && git config user.email "<email>"
    #       - name: Deploy
    #         run: npm run deploy