name: Deploy to Github Pages
on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'PROD'

    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm run openstudio-build && sed -i 's/\/static/static/g' dist/index.html
      - run: cp -r icons/ dist/ && cp site.webmanifest dist/ && cp browserconfig.xml dist/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.