name: Deploy to Github Pages
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'PROD'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm run build
      - run: xvfb-run npm run test
        env: 
          DISPLAY: 99.0
          DBUS_SESSION_BUS_ADDRESS: '/dev/null'
      - run: npm run openstudio-build && sed -i 's/\/static/static/g' dist/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.