name: Test on branch push
on: push

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'PROD'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --ignore-engines --frozen-lockfile --non-interactive
      - run: xvfb-run yarn test
        env:
          DISPLAY: 99.0
          DBUS_SESSION_BUS_ADDRESS: '/dev/null'
